[package]
name = "settings-schema"
version = "0.2.7"
edition = "2024"
publish = false

[[bin]]
name = "settings-schema-checker"
path = "src/bin/settings_schema_checker.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
toml = "0.8"
cel = { version = "0.13", default-features = false, features = ["regex"] }
